#Workflow

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -13,77 +13,69 @@ jobs:
     strategy:
       matrix:
         node-version: [20.x]
-        
 
     env:
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: ${{ secrets.AWS_REGION }}
-        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID}}
-        ECR_REPOSITORY: xpensea-backend
-        IMAGE_TAG: latest
-     
+      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+      AWS_REGION: ${{ secrets.AWS_REGION }}
+      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+      ECR_REPOSITORY: xpensea-backend
+      IMAGE_TAG: latest
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v3
-  
+
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
 
-  
       - name: Login to Amazon ECR
         id: login-ecr
         uses: aws-actions/amazon-ecr-login@v1
-  
+
       - name: Build and Push Docker image
-        id:  build-and-push-image
+        id: build-and-push-image
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          ECR_REPOSITORY: xpensea-backend
-          IMAGE_TAG: latest
+          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
+          IMAGE_TAG: ${{ env.IMAGE_TAG }}
+        run: |
+          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
+          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
 
-        run: |     
-            docker build -t ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
-            docker push ${{env.ECR_REGISTRY}}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
-      
       - name: Deploy to EC2
         env:
-            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-            AWS_REGION: ${{ secrets.AWS_REGION }}
-            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-            ECR_REPOSITORY: xpensea-backend
-            IMAGE_TAG: latest
-            EC2_INSTANCE_IP: ${{ secrets.XPENSEA-BACKEND}}
-            SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
-            USERNAME: ec2-user
-            PORT: 5050
-            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
-            CONTAINER_NAME: xpensea
-
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ env.ECR_REPOSITORY }}
+          IMAGE_TAG: ${{ env.IMAGE_TAG }}
+          EC2_INSTANCE_IP: ${{ secrets.XPENSEA_BACKEND }}
+          SSH_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
+          USERNAME: ec2-user
+          PORT: 5050
+          CONTAINER_NAME: xpensea
         uses: appleboy/ssh-action@master
         with:
-            host: ${{ env.EC2_INSTANCE_IP }}
-            username: ${{ env.USERNAME }}
-            key: ${{ env.SSH_KEY }}
-              
-            script: |
+          host: ${{ env.EC2_INSTANCE_IP }}
+          username: ${{ env.USERNAME }}
+          key: ${{ env.SSH_KEY }}
+          script: |
+            # Refresh ECR login
+            aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
 
-                # Refresh ECR login
-                aws ecr get-login-password --region ${{ env.AWS_REGION }} | sudo docker login --username AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
-            
-                # Pull Docker Image
-                sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
+            # Pull Docker Image
+            if sudo docker pull ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}; then
+              # Stop and remove the current container if it exists
+              sudo docker stop ${{ env.CONTAINER_NAME }} || true
+              sudo docker rm ${{ env.CONTAINER_NAME }} || true
 
-                sudo docker stop ${{ env.CONTAINER_NAME }} || true
-                sudo docker rm ${{ env.CONTAINER_NAME }} || true
-
-                sudo docker run -d \
+              # Run the new container
+              sudo docker run -d \
                 -p ${{ env.PORT }}:${{ env.PORT }} \
                 --name ${{ env.CONTAINER_NAME }} \
                 ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
-
-                
-        
-          
+            else
+              echo "Docker image not found. Skipping deployment."
+            fi
